apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-pipeline-counter
  namespace: kargo-pipeline-counter
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
