apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-pipeline-counter
  annotations:
    kargo.akuity.io/color: "#2196F3"
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-pipeline-counter
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:sika-training-examples/2026-05-27-t-mobile-gitops-example.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/clusters/tcluster/gitops-ondrejsika/values.yaml
            updates:
              - key: backendImage
                value: ${{ imageFrom("ttl.sh/ondrejsika/counter/backend").RepoURL + ":" + imageFrom("ttl.sh/ondrejsika/counter/backend").Tag }}
              - key: frontendImage
                value: ${{ imageFrom("ttl.sh/ondrejsika/counter/frontend").RepoURL + ":" + imageFrom("ttl.sh/ondrejsika/counter/frontend").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: 'chore(tcluster/gitops-ondrejsika): promote counter backend:${{ imageFrom("ttl.sh/ondrejsika/counter/backend").Tag }} frontend:${{ imageFrom("ttl.sh/ondrejsika/counter/frontend").Tag }} image to dev'
            author:
              name: SikaLabs[bot]
              email: sikalabsbot@sikalabs.com
        - uses: git-push
          config:
            path: ./repo
