apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-pipeline-counter
  namespace: kargo-pipeline-counter
spec:
  interval: 1m0s
  subscriptions:
    - image:
        repoURL: ttl.sh/ondrejsika/counter/backend
        allowTags: "^t-mobile-v[0-9]+"
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
    - image:
        repoURL: ttl.sh/ondrejsika/counter/frontend
        allowTags: "^t-mobile-v[0-9]+"
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
