apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 999
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      initContainers:
        - name: sleep10
          image: busybox
          command:
            - /bin/sh
            - -c
            - sleep 5
      containers:
        - name: redis
          image: redis:8
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - mountPath: /data
              name: redis
