apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webservers
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
                  # name: http
