apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - apache.eks.sikademo.com
      secretName: apache-tls
  rules:
    - host: apache.eks.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache
                port:
                  number: 80
                  # name: http
