apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/ondrej/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 26 Apr 2023 09:45:10 CEST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://127.0.0.1:50541
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 26 Apr 2023 09:45:10 CEST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/ondrej/.minikube/profiles/minikube/client.crt
    client-key: /Users/ondrej/.minikube/profiles/minikube/client.key
