version: "3.8"
name: counter
services:
  app:
    build: .
    image: ttl.sh/ondrej/counter
    networks:
      - traefik
      - default
    labels:
      traefik.enable: "true"
      traefik.http.routers.counter.rule: Host(`localhost`)
    deploy:
      replicas: 2
    # ports:
    #   - 80:80
    platform: linux/amd64
    environment:
      REDIS_HOST: redis-server
  redis-server:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:

networks:
  traefik:
    name: traefik
    external: true
