---
- name: Setup Web Server
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: 0644
    - name: Create user ondrejsika
      include_role:
        name: my_create_user
      vars:
        username: ondrejsika
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCslNKgLyoOrGDerz9pA4a4Mc+EquVzX52AkJZz+ecFCYZ4XQjcg2BK1P9xYfWzzl33fHow6pV/C6QC3Fgjw7txUeH7iQ5FjRVIlxiltfYJH4RvvtXcjqjk8uVDhEcw7bINVKVIS856Qn9jPwnHIhJtRJe9emE7YsJRmNSOtggYk/MaV2Ayx+9mcYnA/9SBy45FPHjMlxntoOkKqBThWE7Tjym44UNf44G8fd+kmNYzGw9T5IKpH1E1wMR+32QJBobX6d7k39jJe8lgHdsUYMbeJOFPKgbWlnx9VbkZh+seMSjhroTgniHjUl8wBFgw0YnhJ/90MgJJL4BToxu9PVnH ondrejsika
    - name: See
      debug:
        msg: "See: http://{{ ansible_host }}"
