---
- name: Set Facts Example
  hosts: all
  gather_facts: false

  tasks:
    - set_fact:
        my_list: []

    - set_fact:
        my_list: "{{ my_list + [0] }}"

    - set_fact:
        my_list: "{{ my_list + [1] }}"

    - debug:
        msg: "{{ my_list }}"
