apiVersion: v1
kind: ServiceAccount
metadata:
  name: kv-reader
  namespace: keyvault-demo
  annotations:
    azure.workload.identity/client-id: "e89e29ef-f26f-4ca8-9a17-7aead0de69d2" # Replace with your Azure AD Application (Service Principal) Client ID
