apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/hello_helm

configMapGenerator:
  - name: hello-helm-values
    namespace: hello-helm
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
