FROM golang:1.26 AS build
WORKDIR /build
COPY . .
RUN \
  --mount=type=cache,target=/root/.cache/go-build \
  CGO_ENABLED=0 go build app.go

FROM gcr.io/distroless/static-debian13
WORKDIR /app
COPY --from=build /build/app .
CMD ["./app"]
EXPOSE 80
