{{ if .Values.backupServerHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backup-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.backupServerHost }}
      secretName: {{ .Values.backupServerHost }}-tls
  rules:
    - host: {{ .Values.backupServerHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backup-server
                port:
                  number: 80
{{ end }}