apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-ak-example-go-redis
spec:
  serviceName: {{ .Release.Name }}-ak-example-go-redis
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: ak-example-go-redis
  template:
    metadata:
      labels:
        app: ak-example-go-redis
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: redis
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /data
              name: redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
