apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ak-example-go
spec:
  selector:
    app: ak-example-go
    release: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: http
