apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: petr
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'petr'
    server: 'https://kubernetes.default.svc'
  - namespace: 'petr-hello-petr'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
