apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  # storageClassName: standard
  volumeName: pvc-5be3a368-403b-4b87-b212-f80d1950d66d
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
