apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: training
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        TEXT: Hello from ArgoCD Training
        replicas: 2
        host: training.lab0.sikademo.com
