apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: a3
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: examples/manifests
    repoURL: git@gitlab.sikademo.com:eon/ondrej3.git
