apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controllers2
  namespace: kafka
  labels:
    strimzi.io/cluster: ceps2
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
        kraftMetadata: shared
