apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ak-example
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: ak-example
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: ak-example
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ required ".Values.image is required" .Values.image }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: COUNTER_API_ORIGIN
              value: {{ required ".Values.COUNTER_API_ORIGIN is required" .Values.COUNTER_API_ORIGIN }}
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
