include:
  - project: 'examples/pss/pss-gitlab-ci'
    file: '/simple_image.gitlab-ci.yml'

variables:
  ARGOCD_APPS_PROJECT_ID: 731
  ARGOCD_APPS_BRANCH: master
  IMAGE_VALUES_FILE_DEV: pss_counter_fe.dev.image.values.yaml
  IMAGE_VALUES_FILE_PROD: pss_counter_fe.prod.image.values.yaml
