apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-brno-consumer
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello-brno-consumer
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://gitlab.sikademo.com/egd/argocd-apps-egd.git
      path: ./clusters/egd/hello_brno_consumer/manifests
