apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  # storageClassName: standard
  volumeName: pvc-30688f27-9947-470d-8203-88f24219be06
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
