apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-manifests
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-manifests
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://gitlab.sikademo.com/egd/example-manifests.git
    path: .
