apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iceland
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - iceland.jeddah0.sikademo.com
      secretName: webservers-tls
  rules:
    - host: iceland.jeddah0.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iceland
                port:
                  number: 80