apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4TnpBeU9EYzJOVFU1TUI0WERUSXpNVEl4T0RBMU1UVTFPVm9YRFRNek1USXhOVEExTVRVMQpPVm93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjd01qZzNOalUxT1RCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGMElRTWhJV0tFSmpMV240aU9mS0xxTTZhNmk1dE9vd3l2UUgxMTEKbkhPL0dHem1hMjVlRXlFaGc0WVBNcEpWZFB5d3ZhTDdFMjliVzVyU3RFcGFMWm1qUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVFptY0JRVnFhMEJ4ejRqbFhKClRGVkcxYm5pT0RBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCaFBza2xlTWx3R2VKNWJZNDlibmpURitCMndLOS8KUHExSnFObks2YlFLdWdJZ0pjK2huZFAwVTBRM3BoeHlmRXB6OW5jbktVMDNZVzFsQmw0amo3bit3Vkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://k8s-api.sikademo.com:6443
  name: jeddah
contexts:
- context:
    cluster: jeddah
    namespace: lab0
    user: jeddah
  name: jeddah
current-context: jeddah
kind: Config
preferences: {}
users:
- name: jeddah
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFidW9Oc1RFUW5WV01yRTkteWpscmtGcDdiZE5DWFlrazF0ZlVlRU9PdXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJya2UyIl0sImV4cCI6MjA2MzA3MjQ0MSwiaWF0IjoxNzAzMDc2MDQxLCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoia3ViZS1zeXN0ZW0iLCJzZXJ2aWNlYWNjb3VudCI6eyJuYW1lIjoiYWRtaW4tdXNlciIsInVpZCI6ImRmMzNmZWE0LTVkYjUtNDQ5MS05MmY2LTA3YTcxOGQxYTU0ZCJ9fSwibmJmIjoxNzAzMDc2MDQxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YWRtaW4tdXNlciJ9.PemkCTKY8m80hgZGrLPS9MJZoENvsywfqJzHSE_4cJxwrc3TKBmHTG839PqAS8UuhN_j5sCECG5XbLFDmpx-rz3H0lO230S-Jg-PJGRWxOtDnUMWBK1TUH64_3BIYEkOzo-Shp-dwuYyos7RnrH_0I6V8YAynbgsz-3piQNiVC8qOKxtodk7yKbHiVu3jpY4xxAGbqWYsWSGQOtPg_R9tZJ481V4DJhh2u4iQQrTFU7rOVv9O1RLq5EFmKM6pF2lPIdW0aMK1FRGbLjnQvYxOPW26zVqyvbfn0bwAuhcqH42fn3lIMjCVPkIMDiZnbISDvqPwgf_g6gf1HQwR0UEWQ
