apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: ghcr.io/ondrejsika/training-example
          env:
            - name: TEXT
              value: {{ .Values.TEXT | quote }}
            - name: TEXT_SUFFIX
              value: {{ .Values.TEXT_SUFFIX | quote }}
          ports:
            - containerPort: 80
          startupProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 2
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 1
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 20m
              memory: 20Mi
