apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webservers2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - foo-bar-baz.eon.sikademo.com
      secretName: foo-bar-baz.eon.sikademo.com-tls
  rules:
    - host: foo-bar-baz.eon.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
