apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-vault-secret-data-from
  namespace: vault-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: secret/example
