apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: openshift-operators-redhat
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://gitlab.sikademo.com/egd/argocd-apps-egd.git
      path: ./clusters/egd/_system/loki_operator/manifests
