apiVersion: v1
kind: Service
metadata:
  name: hello-world-loadbalancer-metallb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.114.0.210
spec:
  type: LoadBalancer
  selector:
    app: example
  ports:
    - port: 80
