---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello
  namespace: lab0
spec:
  encryptedData:
    hello: AgCunQKnwc9jMlZFEu2eZ5jV6FlmFTRO64tDk6gW/PBTWMd7ZURiowXFPn1aCkTKpSfoZoHGGRxA7Ek5zsUaLyksDU7xEGEBGHg3Kq9HbC045nn43JaYhj7kyAmsNmgNETYPUqRN+GrQJnzChnE1xXx/9woOQkMQyW/FNkTo6uGw+bOTek9KwANN88AGD1iy1b13UAPS+oDgvUT6YZqdIxpOfrTjtAGv0auT0ETCwTTuDA1jHzF58QUugivA5uF8zexgxQ59JLbuRqBoKHDrc2xyb/4WpockLmH9WlB2KLehmjodakBCZ9pwgGQZtDfiYCY1edepB/ZVenJgHapxz2g7sMTncvVvcg9oE3NKATVqso2oM6k/ee+/QaAfnVckl6biXHddETdjymBHe9FTux8YO8FAAQAvQ4KcDdS3jCy3WVJjljjepN6hPunIHptFwZ/LBq71oJojhrF19qDBwGyiR+wUHts7W5GYW2VIWqXwx671gbU89ZWD6pX1u5owsttxdm0ncKPxeei5YNP74ByrLvyumzC39Ov1S6rJ/uz2OG9+10MAnkjuPerYxXkR2hV6E1g3sEbh/na2cu91wBJ3+I6nbr+DaSHsn4ZZMHn7BNsgiC7IQNk7tl5zEXBnbuUGTyAirx5swAOOpGyvkx0PsiRgtehDR5wEpugjuATUi0c/pM7AAPQbmDm+kBBT5gZufchM1A==
  template:
    metadata:
      creationTimestamp: null
      name: hello
      namespace: lab0
