apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egd-kafka-example
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: egd-kafka-example
  destination:
    namespace: egd-kafka-example
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://gitlab.sikademo.com/egd/egd-kafka-example.git
      path: ./kubernetes/manifests
