---
- name: String Replacement
  hosts: localhost
  gather_facts: false
  vars:
    name: Bella

  tasks:
    - name: Template
      shell:
        cmd: slu file-utils replace-string -i index_string_replacement.template.html -o index_string_replacement.html -f ===NAME=== -r {{ name }}

- name: Deploy index.html
  hosts: all
  gather_facts: false
  tasks:
    - name: Copy index.html
      copy:
        src: index_string_replacement.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: 0600
    # - name: Allow port 80
    #   community.general.ufw:
    #     rule: allow
    #     port: 80
    #     proto: tcp