---
- name: Norway Problem
  hosts: localhost
  gather_facts: false

  tasks:
    - debug:
        msg: "{{ item }}"
      loop:
        - cz
        - sk
        - se
        - no
        - "no"
        - yes
