apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "1"
  name: grafana-datasource-prometheus-external
  namespace: prometheus-stack
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: External Prometheus (k8s)
      type: prometheus
      uid: prometheus-external-k8s
      url: http://prom.sikademo.com:9090
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 30s
