apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: azure-keyvault
  namespace: keyvault-demo
spec:
  provider:
    azurekv:
      tenantId: f2d0a0f9-bb6c-4645-80d0-0481dcc90588 # Replace with your Azure AD Tenant ID
      vaultUrl: "https://aks-kv-example-260514.vault.azure.net" # Replace with your Azure Key Vault URL
      authType: WorkloadIdentity
      serviceAccountRef:
        name: kv-reader
        namespace: keyvault-demo
