{{ if .Values.vaultEnvSecretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-env
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Release.Name }}-env
  dataFrom:
    - extract:
        key: {{ required ".Values.vaultEnvSecretPath is required" .Values.vaultEnvSecretPath }}
{{ end }}
