apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-08-31_counter_helm.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: counter
      values: |
        replicas: 3
        host: counter.os2.oxs.cz
