apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-openshift-custom-domain
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: openshift-default
  tls:
    - hosts:
        - hello.egd.sikademo.com
      secretName: egd-new-tls
  rules:
    - host: hello.egd.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-clusterip
                port:
                  number: 80
