apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      initContainers:
        - name: wait-1s
          image: busybox
          command:
            - /bin/sh
            - -c
            - sleep 1
        - name: wait-for-migrations
          image: registry.k8s.io/kubectl:v1.36.0
          command:
            - kubectl
            - wait
            - --for=condition=complete
            - --timeout=600s
            - job/migrations
      containers:
        - name: backend
          image: ttl.sh/ondrejsika/counter/backend
          env:
            - name: REDIS
              value: redis
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            failureThreshold: 1
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            failureThreshold: 1
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /readyz
              port: 8000
            failureThreshold: 10
            periodSeconds: 1
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 40Mi
