apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backups
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: haproxy
  tls:
    - hosts:
        - ondrejsika.wo0.sikademo.com
      secretName: ondrejsika.wo0.sikademo.com-tls
  rules:
    - host: ondrejsika.wo0.sikademo.com
      http:
        paths:
          - path: /backups
            pathType: Prefix
            backend:
              service:
                name: backups
                port:
                  number: 80
