terraform-providers-lock:
	@(cd ../.. && make _terraform-providers-lock ENV=prod)

terraform-init-state:
	@(cd ../.. && make _terraform-init-state ENV=prod)

infracost:
	@(cd ../.. && make _infracost ENV=prod)
