apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing
spec:
  tls:
    - secretName: cert
      hosts:
        - ing.apps.okd92.aws0.sikademo.com
  rules:
    - host: ing.apps.okd92.aws0.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example
                port:
                  number: 80
