apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    namespace: counter-from-helm
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2026-04-29_adecco_counter_helm.git
    path: .
    helm:
      valuesObject:
        # https://github.com/sika-training-examples/2026-04-29_adecco_counter_helm/blob/master/values.yaml
        host: counter-from-helm.aks.sikademo.com
        hostJs: counter-from-helm-js.aks.sikademo.com