# https://github.com/sikalabs/charts/blob/master/charts/hello-world/values.yaml

host: hello-standa.apps.egd.germanywestcentral.aroapp.io
replicas: 3
TEXT: "Hello standa"
TEXT_SUFFIX: v2
COLOR: blue
BACKGROUND_COLOR: lightblue

ingressClassName: openshift-default
ingressTlsDisable: true
ingressExtraAnnotations:
  route.openshift.io/termination: edge
  route.openshift.io/insecureEdgeTerminationPolicy: Redirect
