{
 "title": "Metgen Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values({job=\"metgen\"}, path)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values({job=\"metgen\"}, method)"
    }
   },
   {
    "name": "status_code",
    "query": {
     "query": "label_values({job=\"metgen\"}, status_code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metgen Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(example_request_duration_seconds_count{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}[5m])",
     "legendFormat": "{{instance}} {{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Metgen Toatal Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(example_request_duration_seconds_count{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}[5m])) by (method, status_code,path)",
     "legendFormat": "{{instance}} {{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Metgen Average Request Duration by path only",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(example_request_duration_seconds_sum{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}) by (path) / sum(example_request_duration_seconds_count{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"})  by (path)",
     "legendFormat": "{{instance}} {{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Metgen Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(example_request_duration_seconds_sum{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}) by (method, status_code, path) / sum(example_request_duration_seconds_count{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"})  by (method, status_code, path)",
     "legendFormat": "{{instance}} {{method}} {{path}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Metgen Request Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(example_request_duration_seconds_bucket{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}) by (le) / ignoring(le) group_left sum(example_request_duration_seconds_count{job=\"metgen\", path=~\"$path\", method=~\"$method\", status_code=~\"$status_code\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}