apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: praha-hello
  namespace: kafka
  labels:
    strimzi.io/cluster: praha
spec:
  partitions: 27
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
