version: "3.9"
name: counter
services:
  counter:
    build: ./counter
    image: ${IMAGE_COUNTER:-reg.istry.cz/ondrej/counter}
    labels:
      traefik.enable: true
      traefik.frontend.rule: Host:${HOST:-localhost}
    depends_on:
      redis:
        condition: service_healthy
  redis:
    build: ./redis
    image: ${IMAGE_REDIS:-reg.istry.cz/ondrej/redis-slow}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 1s
      start_period: 5s
volumes:
  redis-data:
