up:
	docker compose up -d --remove-orphans

down:
	docker compose down --remove-orphans

down-with-volumes:
	docker compose down --remove-orphans --volumes

use-ports:
	cp .env.ports .env

use-tests:
	cp .env.tests .env

use-traefik:
	cp .env.traefik .env

use-external-traefik:
	cp .env.external-traefik .env
