# https://github.com/sikalabs/charts/blob/master/charts/hello-world/values.yaml

host: hello-tch.apps.egd.germanywestcentral.aroapp.io
replicas: 3
TEXT: "Hello tch"
TEXT_SUFFIX: v2
COLOR: black
BACKGROUND_COLOR: yellow

ingressClassName: openshift-default
ingressTlsDisable: true
ingressExtraAnnotations:
  route.openshift.io/termination: edge
  route.openshift.io/insecureEdgeTerminationPolicy: Redirect
