apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kargo
  namespace: kargo
spec:
  releaseName: counter
  chart:
    spec:
      chart: ./charts/kargo
      sourceRef:
        kind: GitRepository
        name: kargo
        namespace: kargo
      version: "*"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: kargo-values
      valuesKey: values.yaml
