apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  revisionHistoryLimit: 0
  replicas: 20
  strategy:
    # type: RollingUpdate
    # rollingUpdate:
    #   maxSurge: 0
    #   maxUnavailable: 1
    type: Recreate
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        svc: example
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example:green
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 30m
              memory: 30Mi
            limits:
              memory: 50Mi
              cpu: 50m
