# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
# https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=values
controller:
  service:
    type: ClusterIP
  ingressClassResource:
    default: true
  kind: DaemonSet
  hostPort:
    enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  config:
    enable-access-log: "true"
    log-format-upstream: >-
      $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent
      "$http_referer" "$http_user_agent" "$request_length" "$request_time" "$upstream_response_time"
      "$host"
defaultBackend:
  enabled: true
  image:
    registry: ghcr.io
    image: sikalabs/sikalabs-kubernetes-ingress-default-page
    tag: latest
    pullPolicy: Always
  extraEnvs:
    - name: CLUSTER
      value: "lab0"
    - name: DOMAIN
      value: "lab0.sikademo.com"
  port: 8000