apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.2
      helm:
        valueFiles:
          - $values/apps/lab0/_system/ingress-nginx/ingress-nginx.values.yaml
    - repoURL: https://gitlab.sikademo.com/training/ondrejsika-argocd-apps.git
      ref: values
