apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIrZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWtNU0l3SUFZRFZRUUREQmx5YTJVeUxYTmwKY25abGNpMWpZVUF4TnpBeU9EYzJOVFU1TUI0WERUSXpNVEl4T0RBMU1UVTFPVm9YRFRNek1USXhOVEExTVRVMQpPVm93SkRFaU1DQUdBMVVFQXd3WmNtdGxNaTF6WlhKMlpYSXRZMkZBTVRjd01qZzNOalUxT1RCWk1CTUdCeXFHClNNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJGMElRTWhJV0tFSmpMV240aU9mS0xxTTZhNmk1dE9vd3l2UUgxMTEKbkhPL0dHem1hMjVlRXlFaGc0WVBNcEpWZFB5d3ZhTDdFMjliVzVyU3RFcGFMWm1qUWpCQU1BNEdBMVVkRHdFQgovd1FFQXdJQ3BEQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRV0JCVFptY0JRVnFhMEJ4ejRqbFhKClRGVkcxYm5pT0RBS0JnZ3Foa2pPUFFRREFnTkhBREJFQWlCaFBza2xlTWx3R2VKNWJZNDlibmpURitCMndLOS8KUHExSnFObks2YlFLdWdJZ0pjK2huZFAwVTBRM3BoeHlmRXB6OW5jbktVMDNZVzFsQmw0amo3bit3Vkk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://k8s-api.sikademo.com:6443
  name: cluster
contexts:
- context:
    cluster: cluster
    namespace: prague
    user: user
  name: prague-namespace-in-jeddah-cluster
current-context: prague-namespace-in-jeddah-cluster
kind: Config
preferences: {}
users:
- name: user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjFidW9Oc1RFUW5WV01yRTkteWpscmtGcDdiZE5DWFlrazF0ZlVlRU9PdXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJya2UyIl0sImV4cCI6MTcwMzA4MDIyNCwiaWF0IjoxNzAzMDc2NjI0LCJpc3MiOiJodHRwczovL2t1YmVybmV0ZXMuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCIsImt1YmVybmV0ZXMuaW8iOnsibmFtZXNwYWNlIjoicHJhZ3VlIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InByYWd1ZSIsInVpZCI6IjY0OTM3ZTk4LTUyN2MtNDNkZi05YTQzLTAxYmUwMzY0ZDE4ZSJ9fSwibmJmIjoxNzAzMDc2NjI0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6cHJhZ3VlOnByYWd1ZSJ9.Qw29_5t2XlzJAj0HU4omQrWIBYvGIvLNM-xrtmREWCm8Un8RsfGf9Mws65I2Nn4umGjfdcb-EieW604GfB-8SmWHhaXO-FoOx_3u40-2fX2eV3VoKnqChhCrrkVJeR7ZoBZGUZPd75gW-lduoASJ19lbN2Xsk9jgeW6U-6j3gTYbq5MiDNG0tV3lsEOdDHqyN1YDdxMaOwBK-s6AfgUFIj9Nw5PxR0xAARr7QywGjKIYwVdNG9LnGEekXLwnu3m-y9Ac4-Ja_FmA2RS-8r6YnQYuJtL_tQhDqkhYfULOV12LZ3ewDl8ZmYZVJ_xr0RvaXD3zsLicuga9zkPw1uZf6g

