global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "metgen"
    static_configs:
      - labels:
          env: "prod"
        targets:
          - "localhost:8000"
          - "localhost:8001"
      - labels:
          env: "dev"
        targets:
          - "localhost:8002"

  - job_name: node
    static_configs:
      - targets:
          - lab0.sikademo.com:9100
          - lab1.sikademo.com:9100
          - lab2.sikademo.com:9100
          - lab3.sikademo.com:9100
          - lab4.sikademo.com:9100

  - job_name: blackbox
    static_configs:
      - targets:
          - prom.sikademo.com:9115
          - lab0.sikademo.com:9115

  - job_name: http
    metrics_path: /probe
    static_configs:
      - targets:
          - https://ondrejsika.com
          - https://ondrejsika.int
          - https://sika.io
          - https://sika.int
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: lab0.sikademo.com:9115

  - job_name: cadvisor
    static_configs:
      - targets:
          - lab0.sikademo.com:9338
          - lab1.sikademo.com:9338
          - lab2.sikademo.com:9338
          - lab3.sikademo.com:9338
          - lab4.sikademo.com:9338
          - prom.sikademo.com:9338
          - vm0.sikademo.com:9338
          - vm1.sikademo.com:9338
          - vm2.sikademo.com:9338

  - job_name: postgres
    static_configs:
      - targets:
          - lab0.sikademo.com:9187

  - job_name: file-sd
    file_sd_configs:
      - files:
          - service-discovery-file.yml
        refresh_interval: 5s

  # - job_name: consul
  #   consul_sd_configs:
  #     - server: lab0.sikademo.com:8500
  #       tags:
  #         - prometheus
  #   relabel_configs:
  #     - source_labels: [__meta_consul_service]
  #       target_label: job
  #     - source_labels:
  #         - __meta_consul_node
  #       target_label: instance

  - job_name: push-gw
    metric_relabel_configs:
      - source_labels: [exported_job]
        target_label: job
      - source_labels: [exported_instance]
        target_label: instance
      - regex: "exported_instance|exported_job"
        action: labeldrop
    static_configs:
      - targets:
          - prom.sikademo.com:9091

  - job_name: push-gw-2
    static_configs:
      - targets:
          - 127.0.0.1:9091

  - job_name: "example-random"
    static_configs:
      - targets:
          - "localhost:8080"
          - "localhost:8081"
        labels:
          env: "prod"
      - targets:
          - "localhost:8082"
        labels:
          env: "dev"

  - job_name: "ex1"
    static_configs:
      - targets:
          - "localhost:8000"

  - job_name: "ex2"
    static_configs:
      - targets:
          - "localhost:8001"

rule_files:
  - prometheus.rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093"
