apiVersion: v1
kind: PersistentVolume
metadata:
  name: aaa
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: file.csi.azure.com
    volumeAttributes:
      skuName: Standard_LRS
    volumeHandle: MC_training_training_germanywestcentral#fe7db152d821548da96d84d#aaa###xxx
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem