apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: k-4
  namespace: kafka
  labels:
    strimzi.io/cluster: k-4
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
        kraftMetadata: shared
