apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: k-4
  namespace: kafka
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: extplain
        port: 9094
        type: nodeport
        tls: false
      - name: exttls
        port: 9095
        type: nodeport
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 3
      default.replication.factor: 3
      min.insync.replicas: 3
  entityOperator:
    topicOperator: {}
    userOperator: {}
