apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: egd-foo
  namespace: kafka
  labels:
    strimzi.io/cluster: egd
spec:
  topicName: foo
  partitions: 27
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
