apiVersion: kafka.strimzi.io/v1
kind: KafkaMirrorMaker2
metadata:
  name: mm2
  namespace: kafka
spec:
  version: 4.2.0
  replicas: 3
  target:
    alias: ceps2
    bootstrapServers: ceps2-kafka-bootstrap.kafka.svc:9092
    groupId: mm2
    configStorageTopic: mm2-configs
    offsetStorageTopic: mm2-offsets
    statusStorageTopic: mm2-status
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
    - source:
        alias: ceps
        bootstrapServers: ceps-kafka-bootstrap.kafka.svc:9092
      sourceConnector:
        tasksMax: 3
        config:
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: "false"
          # Mirror only topics matching this regex
          topics: "df.*"
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
          sync.group.offsets.enabled: "true"
