terraform-providers-lock:
	@(cd ../.. && make _terraform-providers-lock ENV=dev)

terraform-init-state:
	@(cd ../.. && make _terraform-init-state ENV=dev)

infracost:
	@(cd ../.. && make _infracost ENV=prod)
