apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ammar
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello-ammar.jeddah1.sikademo.com
      secretName: hello-ammar.jeddah1.sikademo.com-tls
  rules:
    - host: hello-ammar.jeddah1.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-ammar
                port:
                  number: 80