apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: 1.16.3
      helm:
        valueFiles:
          - $values/apps/lab0/_system/cert-manager/cert-manager.values.yaml
    - repoURL: https://gitlab.sikademo.com/training/ondrejsika-argocd-apps.git
      ref: values
