apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-vault-secret
  namespace: vault-demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
    - secretKey: FOO
      remoteRef:
        key: secret/example
        property: FOO

    - secretKey: BAR
      remoteRef:
        key: secret/example
        property: BAR
