apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  # storageClassName: do-block-storage-retain
  # volumeName: pvc-b1f79e52-fda0-48af-8221-fba3d912140b
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
