apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: null
  labels:
    machine.openshift.io/cluster-api-cluster: demo-gf2pd
  name: demo-gf2pd-worker-eu-central-1c
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: demo-gf2pd
      machine.openshift.io/cluster-api-machineset: demo-gf2pd-worker-eu-central-1c
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: demo-gf2pd
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: demo-gf2pd-worker-eu-central-1c
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          ami:
            id: ami-0f2fb62b5e1da79bd
          apiVersion: machine.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 0
              kmsKey:
                arn: ""
              volumeSize: 120
              volumeType: gp3
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: demo-gf2pd-worker-profile
          instanceType: m6i.xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          metadataServiceOptions: {}
          placement:
            availabilityZone: eu-central-1c
            region: eu-central-1
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - demo-gf2pd-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - demo-gf2pd-private-eu-central-1c
          tags:
          - name: kubernetes.io/cluster/demo-gf2pd
            value: owned
          userDataSecret:
            name: worker-user-data
status:
  replicas: 0
