apiVersion: v1
kind: ConfigMap
metadata:
  name: root-ca
  namespace: kube-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDEDCCAfigAwIBAgIIOlnXEsNsFR8wDQYJKoZIhvcNAQELBQAwJjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdyb290LWNhMB4XDTIyMTIyMDIxNTAwNloX
    DTMyMTIxNzIxNTAwNlowJjESMBAGA1UECxMJb3BlbnNoaWZ0MRAwDgYDVQQDEwdy
    b290LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2/shRt3zL3+M
    JEsvKgPD5cDi4kfAENDLxoeTKuc2/nYw/MZKtv2Y5p1G67ztlezN7JGFoNYCjoGE
    VpFFBjtKSuAb7TYrOBcvUd+xa8L8LiIJDC1hHOPiHeJ5vdHDtY8FkS4+BzH1th/Y
    6xDecEAd7ZZg3ggXXRxjFcV88a47TdAOMcBDfDe5w3NQxIzsFMgnFJ4WYCdU43vc
    ryvdmR+M0+MtqI/0b9OdePbdXlb71tN0/OxL0oOoq6mx8KYdRHhxr5y0KJxqzzq8
    slyq4PL5HedizI16Xgnx/z/ForT18ZmFM918hVgVKO/sabolyDZ99NF33AVMUB6P
    Knv3llrIIQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQU9bNDQHks7tYaRC3/BLAIPDQCh7swDQYJKoZIhvcNAQELBQAD
    ggEBAKO88Z344iMcQ8wrVNPj6ZMB35DgRqDSG0i1YhHtDdoelG8jgGjdfNZsr647
    qUaRL8TDBEtYSO/WQCW0qUk1rFB4I/7YNCHANnmu3h1tK83bMy4c0BrG5Z+OIbZ2
    NpY9UX8kOJdVUXSpx5nsxRC/ZHZUJxwElqjSDa6UJqvy7XiJmprlFJEu82yi3V+V
    pkjTwTrRs4kSapE1yxJcrNzwKWNbhHRM3IMVb0dB4XExatX4wFLN/SMvXWwDeDm8
    ZOqV+2EzOj0Tn3jbZDgtDUl+2hAZEjhPiVB0e3YDXhLHBfdw6JBm0zIOWqXWAfni
    jjC739UEULJMiQITbqUeH1GcNLE=
    -----END CERTIFICATE-----
    
