apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: my-cluster-foo
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: foo
  partitions: 27
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
