apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-root-password
spec:
  refreshInterval: "1m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: {{ .Release.Name }}-root-password
  dataFrom:
    - extract:
        # key: MONGODB_ROOT_PASSWORD
        key: {{ required ".Values.vaultMongoDBRootPasswordSecretPath is required" .Values.vaultMongoDBRootPasswordSecretPath }}
