apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpVeE9EZ3lNVEF3SGhjTk1qVXhNakE0TVRBd016TXdXaGNOTXpVeE1qQTJNVEF3TXpNdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpVeE9EZ3lNVEF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMnlRdllXNGtJaG1ObENHK050ZC9HN3cxb0hhQ1VQS1hoSUZaUFl4amYKdHBlKzkwSk11dm5iclVzL3lzZTBEMUZ5czF0VmtMSEhTQXZoTndINGhTK2JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTM1d2x6U0RxN1VrOXE3ZE4zY0VECnVTL2dRSTB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUszTUQvVjJhR3d6ZXRVMWxnRC9XWEJRQTdtL0lyZG4KQSsraG5ORFl4OElRQWlCaHIyUjE4aTgxS0MrNUFRS1Ivd1hpS1VLUDcraGxwV2poUTBmUEZISDREQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0.0.0.0:38187
  name: k3d-default
contexts:
- context:
    cluster: k3d-default
    namespace: counter
    user: pepa
  name: k3d-default
current-context: k3d-default
kind: Config
preferences: {}
users:
- name: pepa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ims1am56OXdUR1YzTUZvcGxxd2hYOVZSUUJ5ZjJYNXRRellGV0JjTnJOdEkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY4ODY5NDMzLCJpYXQiOjE3NjUyNzMwMzMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNTc3OGNlMWMtZDRkNy00NDE3LWE5ZjItZjU5ZWYwYTZjM2JmIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJjb3VudGVyIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InBlcGEiLCJ1aWQiOiJiOGY5ZWMwMC00MmY0LTQ5MWYtOWNmNi0yNDIxZTg1M2ViZjYifX0sIm5iZiI6MTc2NTI3MzAzMywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmNvdW50ZXI6cGVwYSJ9.oH6Zng4NULUnY_95v3NxghSYnLZMoprL6NqpOYfrLUVat9BjGIpfgkLBlgiZPwTCLt6QNr44K9iMTH68JP2P2jI19Y14nVbeGtuNaNEdA_t6AC_y2bOOQ37yL1Jn-3YtzIXhBM5NsGCqLnZGTPiuIqX-a8mKH95gABNqnf90LpBgnt-IiwYCSpOTpeaX-ONtyYatwJtbmet3YeV71lVynhan4wjv4jPHvN5XpQHOKr20oFyxj9EdMNzY5-OubdRFLtmo0ShpUUjmORN2lK5wAIV6HrumdPQSW6URHKiwfa3BtNxE04DzeHLNV-G_eETojLIggLPRa6VDXJZbiL8S1w
