apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTmpVeE9EZ3lNVEF3SGhjTk1qVXhNakE0TVRBd016TXdXaGNOTXpVeE1qQTJNVEF3TXpNdwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTmpVeE9EZ3lNVEF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTMnlRdllXNGtJaG1ObENHK050ZC9HN3cxb0hhQ1VQS1hoSUZaUFl4amYKdHBlKzkwSk11dm5iclVzL3lzZTBEMUZ5czF0VmtMSEhTQXZoTndINGhTK2JvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTM1d2x6U0RxN1VrOXE3ZE4zY0VECnVTL2dRSTB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUszTUQvVjJhR3d6ZXRVMWxnRC9XWEJRQTdtL0lyZG4KQSsraG5ORFl4OElRQWlCaHIyUjE4aTgxS0MrNUFRS1Ivd1hpS1VLUDcraGxwV2poUTBmUEZISDREQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0.0.0.0:38187
  name: k3d-default
contexts:
- context:
    cluster: k3d-default
    namespace: counter
    user: franta
  name: k3d-default
current-context: k3d-default
kind: Config
preferences: {}
users:
- name: franta
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ims1am56OXdUR1YzTUZvcGxxd2hYOVZSUUJ5ZjJYNXRRellGV0JjTnJOdEkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY4ODY5Mzk3LCJpYXQiOjE3NjUyNzI5OTcsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMzM5NzJlMzMtOTdkMC00YTEzLTkyZmItMGI3MzZmODQ3ZTliIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJjb3VudGVyIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImZyYW50YSIsInVpZCI6IjAwMzcxNGEzLWIwNWEtNDhmYS1hOGI3LTZmNWYzMTFkZTRiZiJ9fSwibmJmIjoxNzY1MjcyOTk3LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y291bnRlcjpmcmFudGEifQ.Wqt3dbv5xbIrDfHdKXZFrYGL0SqiYEPgGIuoeu9h4JWlgKAYoAhXJX_WwdEhIvAU4xU9QkEW52j0dMgTNGRSnAVb_RTR0D6TIqTp7_-BY7XelRXTZo9TKdsyQsuI17aAPDhr33CYUlY46fJvM1UMG_TQOL9WJoG6Zg6Zn4TghKOVx_rgMNWfRl2rVDHdkF9uI0DJJ6yypBCvVw3rKu3tF0x2KiCOUd27tS4LhZ0kUJEBE6Irk_yUGEfnDhc9hvH2qhzEU4fG62bBSeKdsnXgY-hgJEAhdhDuI68OIRN4lCKrOY77SvYIe1-mEqaJXyKf8lF1Vl3_ovue1dzGiYYPxA
