apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  storageClassName: local-path-retain
  # volumeName: pvc-696db1de-9e94-4698-a2bb-49d10b37fff6
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
