FROM debian:12-slim AS build
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt --break-system-packages

FROM gcr.io/distroless/python3-debian12
WORKDIR /app
COPY --from=build /usr/lib/python3.11/dist-packages/ /usr/lib/python3.11/dist-packages/
COPY . .
CMD ["app.py"]
EXPOSE 80
