apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: counter
spec:
  rules:
    - host: counter.jeddah0.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: counter
                port:
                  number: 80
