global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "localhost:18080"
          - "docker.sikademo.com:18080"
  - job_name: "traefik"
    static_configs:
      - targets:
          - "docker.sikademo.com:8080"
