apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: kafka
data:
  init.sql: |
    CREATE TABLE users (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      email VARCHAR(100) UNIQUE NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE pets (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      kind VARCHAR(50) NOT NULL,
      owner_id INT REFERENCES users(id),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-init-sql
          configMap:
            name: postgres-init-sql
      containers:
        - name: postgres
          image: postgres:18
          args:
            - -c
            - wal_level=logical
          env:
            - name: POSTGRES_DB
              value: example
            - name: POSTGRES_PASSWORD
              value: pg
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-init-sql
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kafka
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
