apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/flux
- kustomization_tenants.yaml
- kustomization_hello_us.yaml
- kustomization_hello_us_helm.yaml
- kustomization_ondrejsika.yaml
