apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: egd-foobar
  labels:
    strimzi.io/cluster: egd
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: foo
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: "*"
      - resource:
          type: topic
          name: bar
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: "*"
      - resource:
          type: group
          name: foo
          patternType: literal
        operations:
          - Read
        host: "*"
      - resource:
          type: group
          name: bar
          patternType: literal
        operations:
          - Read
        host: "*"
