apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: counter
  namespace: gitops-ondrejsika
spec:
  releaseName: counter
  chart:
    spec:
      chart: ./kubernetes/chart
      sourceRef:
        kind: GitRepository
        name: counter
        namespace: gitops-ondrejsika
      version: "*"
  interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: counter-values
      valuesKey: values.yaml
