apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-lab0
  namespace: argocd
spec:
  project: app-of-apps
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - PruneLast=true
  source:
    repoURL: https://gitlab.sikademo.com/training/ondrejsika-argocd-apps.git
    path: apps/lab0
    directory:
      recurse: true
      exclude: '{**/manifests/**,**/Chart.yaml,**/values.y*ml,**/*.values.y*ml,**/templates/**}'
