apiVersion: apps/v1
kind: Deployment
metadata:
  name: df2
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: df2
  template:
    metadata:
      labels:
        app: df2
    spec:
      containers:
        - name: main
          image: ttl.sh/ceps/df2:v2
          env:
            - name: BROKER_ADDR
              value: ceps-kafka-bootstrap.kafka.svc:9092
            - name: TOPIC_IN
              value: df1-out
            - name: TOPIC_OUT
              value: df2-out
            - name: GROUP_ID
              value: df2
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 100m
              memory: 100Mi
