apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-window
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: sync-window
  destination:
    namespace: sync-window
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        # https://github.com/sikalabs/charts/blob/master/charts/hello-world/values.yaml

        host: sync-window.apps.egd.germanywestcentral.aroapp.io
        replicas: 3
        TEXT: "sync-window"
        TEXT_SUFFIX: v3

        ingressClassName: openshift-default
        ingressTlsDisable: true
        ingressExtraAnnotations:
          route.openshift.io/termination: edge
          route.openshift.io/insecureEdgeTerminationPolicy: Redirect
