apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: standa-hello-standa
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: standa
  destination:
    namespace: standa-hello-standa
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: charts/hello-world
      helm:
        valueFiles:
        - '$values/clusters/egd/standa/hello_standa/hello_standa.values.yaml'
    - repoURL: https://gitlab.sikademo.com/egd/argocd-apps-egd.git
      ref: values
