apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  revisionHistoryLimit: 0
  replicas: 4
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello-world-deploy
  template:
    metadata:
      labels:
        app: hello-world-deploy
        svc: example
    spec:
      containers:
        - name: main
          image: ondrejsika/training-example:red
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: PORT
              value: "80"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m