{
 "title": "Custom Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cpu_usage_perc", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_perc", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~\"eth0\"}[1m])*8",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_Active_bytes\n", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 } }
 ]
}