apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://k3s.sikademo.com:6443
  name: k3s
contexts:
- context:
    cluster: k3s
    user: k3s
  name: k3s
current-context: k3s
kind: Config
preferences: {}
users:
- name: k3s
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJWFFGcTR2QzNLSlF3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOekk0T0RrME5UY3pNQjRYRFRJME1UQXhOREE0TWprek0xb1hEVEkxTVRBeApOREE0TWprek0xb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJBVjczU3VjYUFqS1B5SWwKYjRIWlBNZEpHRysyUVNUQThmbG5HM0dvTXVNb2N5bjFRUGpOQXc5UWlJdzJuTGltS3RFTHRNaUJkaVF3T21iVApSZVNleVphalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUjJtSzRHbTdMaUVzRlJpZ0pQRzgvR29VUWwyREFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlFQW0rbEs1OTBhaDh3UXlIc3IzRjIxMU9HMU84WVZoU1hobzl4blhYSEhJYVFDSURQVWxLek9JQjd2b0dRTAozYk54UndYWXlNTU9XbTc5OEE5S2JUWC80ekw2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzTWpnNE9UUTFOek13SGhjTk1qUXhNREUwTURneU9UTXpXaGNOTXpReE1ERXlNRGd5T1RNegpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzTWpnNE9UUTFOek13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUWk9qY1B4eGJleFFYZ1RGSHpWUTkrQnN4QWFRTzM5K2tWVDdYUXI4ZGYKZCsrbW1iTkd4RWJhZ2FFUEhTdEsxWURjb3MvMm1zWW9mSTM2Y2llNFVQQTVvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWRwaXVCcHV5NGhMQlVZb0NUeHZQCnhxRkVKZGd3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnQjlXNzZpamkvWTNuSGJFZTB3REwxOC9CbGMrd0dYRmsKR2pHdWM5czZ6azBDSURVdG04R2lBMUJFcTMxcW1YaURHNCs2SExzSE9Qd2Z4MFYrS0Z6dGtjdFAKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUZLYjZBaTBzOHBVNTVUTnFtZ0VtTXZETzEyTElOVUJTUStuSUFFWFJQSk5vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFQlh2ZEs1eG9DTW8vSWlWdmdkazh4MGtZYjdaQkpNRHgrV2NiY2FneTR5aHpLZlZBK00wRApEMUNJakRhY3VLWXEwUXUweUlGMkpEQTZadE5GNUo3SmxnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
