rsync -av root@lab0.sikademo.com:/training/ lab0.sikademo.com/
rsync -av root@lab1.sikademo.com:/training/ lab1.sikademo.com/
rsync -av root@lab2.sikademo.com:/training/ lab2.sikademo.com/
rsync -av root@lab3.sikademo.com:/training/ lab3.sikademo.com/
rsync -av root@lab4.sikademo.com:/training/ lab4.sikademo.com/
rsync -av root@lab5.sikademo.com:/training/ lab5.sikademo.com/
rsync -av root@lab6.sikademo.com:/training/ lab6.sikademo.com/
rsync -av root@lab7.sikademo.com:/training/ lab7.sikademo.com/
rsync -av root@lab8.sikademo.com:/training/ lab8.sikademo.com/
rsync -av root@lab9.sikademo.com:/training/ lab9.sikademo.com/
rsync -av root@lab10.sikademo.com:/training/ lab10.sikademo.com/
rsync -av root@lab11.sikademo.com:/training/ lab11.sikademo.com/
rsync -av root@lab12.sikademo.com:/training/ lab12.sikademo.com/
rsync -av root@lab13.sikademo.com:/training/ lab13.sikademo.com/
rsync -av root@lab14.sikademo.com:/training/ lab14.sikademo.com/
rsync -av root@lab15.sikademo.com:/training/ lab15.sikademo.com/
rsync -av root@lab16.sikademo.com:/training/ lab16.sikademo.com/
rsync -av root@lab17.sikademo.com:/training/ lab17.sikademo.com/
rsync -av root@lab18.sikademo.com:/training/ lab18.sikademo.com/

