apiVersion: v1
clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV4TWpFeQpNVEF4TkRWYUZ3MDBNekV4TWpFeU1UQXhORFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDODQxcEcxTGR1T0x2R3JPWHFNejhweEluUktVTnpqTnRlWG0xa2RySXpheVVhcTRDegpOaVp4enZWWHZ0MW9JLzJRMCsvNVBieGFxSWx2bUhBdDFMSFFvK3llWmY4c3VTeGoyQ3RwVXNZaGpiaVdhaVpXClZ6Q3JYNGxTM2NxN1NYS0dpODdvY0lGSDlsalE2b1NYR2RCYjlTSEM4UnU3STg1ckpUODFjbDZQbDIvbEI2VG0KSDBNWlRTWi9QTkVWTUx0ZE44RVI1dE85aDlRajFDdWU3b3dIOFNTUU9vSnZCSmIzdDlkYzMwbXpyTjBVaGFJegpzZFM5bzZpLzE3SFZ2Yk1JQUZ4Lyt5eks2eFZ2L3BWUER1Nmc1dGVCYVMwUm5GZFFaRjJ1cXdUaVJtTDVYUDVHCk1SSndjdW5IRkR2UWpFUi9KUE9qQzZPREpRNXF4Y0V4dXRyYkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlM1REJ2ZU1IaWRYeWFXbjIwVQp1RFBSMkplRlpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFnb3RHMjBVZ3lDZ3VzSjRPRm9oS0tEN21SeW5mCnJ4L3hhL0xhdEFqQ3U5WVF1Z1l0QXlHSGxpc0JpSGZ6bVlhU1IvdEtxSFN3V0NhUXJua0tKclpHMk9adHZ5NE8KVTRqRmdYekc3VlZkMjNNTThiVW1PVUlSSGxtbHdKcEEvdDE1eEM3ZzZjL1hJWkhWbCtJNlJOdE9RQkFFdmJaRApvcmUxZGtrR0FlR09RcGtTMXdQd2h6SjNDMXhHMDh0b2tDekgrbWZVOEs5SVM1Nm1xdEhqWURzWU9lcjJRazBiCkFhdk15K1NWZGdhN3RhSmZCempUZDBhOGQxcTZpZ0FKRlI0VmY5a2ZiS2FEalYzODE5bzhKUFJCa0hLUmNUeEkKbC9aeEk5L0JaVUtwenRuNkh2NXRUV1BES2tieFhYbHgzT1lEU1NaOHN0L01xQi9ueHo4cTdSaUduUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://030a346d-79f6-472a-beda-39cc5992bdc5.k8s.ondigitalocean.com
      name: do-fra1-sikademo
contexts:
    - context:
        cluster: do-fra1-sikademo
        namespace: longhorn-system
        user: do-fra1-sikademo-admin
      name: do-fra1-sikademo
    - context:
        cluster: do-fra1-sikademo
        user: metrics
      name: metrics
current-context: do-fra1-sikademo
kind: Config
preferences: {}
users:
    - name: do-fra1-sikademo-admin
      user:
        token: dop_v1_2fd50fcaca281e62f4299b31dbe0306807b64c0e62467b3be1b4eca1841e1af2
    - name: metrics
      user:
        token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjNrNGdqOTBlZl8xOU1VdDdFb285UGd1N19pd0VqZ1ZOUTYtbGItWXNfWGsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRyaWNzLXVzZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibWV0cmljcy11c2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmFkMzM0ZGEtYTUxOS00N2RkLWIzMjctZTVlNDRiNDdhNTI2Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOm1ldHJpY3MtdXNlciJ9.Vso3VSfVm39TLIzfgZm_Q0V2jdrPARlhOeHAfw5kj6MtDiwro93AEFz-9gUNC2ZnCYTXcPOyVh2_naqUkhDmByC5fGpf_ddwHD_8GzAGmuakLse6MAL38WgfqV26FYaL8vW9jiJ5GBhSE96ygpA3xMXi7lQoBZUzNRzhcLhPS4lkpyERjmsvQLraQL2LIbCiq-oANqgqNxhPcgzviA7LdErdG3P4r8_H2uZSMQ9lElMnUZSx9ROkXmTbl-56gUNKYNV6RbxM2tIUnCysp4_6UBQwciPX76CPTe6APncAfFWhLCeb7nlCaxpTkwqMtlQeBhCJ-ni8zl6qw-JvH9KJtQ
