apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  storageClassName: standard-retain
  volumeName: pvc-ac07af0c-52a5-4ff3-8f61-c25327538826
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
