apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://github.com/sika-training-examples/2026-05-15_gitops_dhl_example.git
    path: clusters/aks
    directory:
      recurse: true