apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage-ntfs
parameters:
  fstype: refs
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
