apiVersion: v1
kind: ResourceQuota
metadata:
  name: limits
spec:
  hard:
    requests.cpu: 300m
    requests.memory: 400Mi

    limits.cpu: 600m
    limits.memory: 800Mi

    services.loadbalancers: 0

    # count/deployments.apps: 3
    count/pods: 10
