apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV5TVRBeApOekl3TlRWYUZ3MDBOVEV5TVRBeE56SXdOVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDK1VTeFZLOUd1SEQyVG45Vlo5T1hJb010a3NGNU9pK2M3MEtkMkNnRUdDa2hqOEhBRgpnYXZKbTkxVUdVMzBRWGpRV2ZiVXQrVldDSlBoYUIyRWFkNm9Na0VEc1NoUnZ2Q3FWRndBNDkrVm4vanZhL2VECmM0WDFDYmxyR1o0bTZ6QmhoQUlBUXREVXgyaDNWbHY2TDRiVjBtcnRjbnhsYXk5aGVxcGg3dmphYWZ5Y3BKTGkKRDFmSkVRNkljdTZaT1pJQWFNeHUwS0FCRjJ5MmYrUVM1R1ZKMmZMM29JRDRETnE4QWd3UVJrVTdUUzJtaTFRWQpCdEdHUHFpQWhwV3k1dHljV21hZStaOW10ekxKME1oQ3l2Ly82S2J0TGpmejRERGJLWWZSRElsZFMrUXhWQk9RCitmb3R0WDFoSUh0M1g3Y2dhN3dHTnlKejUvTVEwaWNpbTNQTEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRSVnNPQmUvTjJNaXJ0QXhibQo3MEw0Uzd4MDlqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNVmsvazlmb1E5dk9GaTdKSnFqN1BxQ1FZMGlKCmVkMWNWUnBCL0YzaUlCUVAwUjlFREJSYTFjTHRPSFNXSnUwUkloYWFYNTNvU2hRWTZhcGlFVjhza29qRGNhMU4KU0ZpenBhNVNnTjR0WHFNWlF3K3dnWUJZZFJrVXdQQVZIcDIyUXViN0M3djBMZVMweE8xRzNTTE8xeWxKNUdpMwpCdUR4STNJdTl0dk92T2NYNUtnQk1lSzcrbitISjRGYkZkb3pLcnpHc3RWZmdMSXZLQ1lsYzBSWU1lL3Z1Z0g2CmdVUmZ2bnk5M2pHMksrUTV0c1ZzdkpDMWR6NFlPVmtWY0lpNC9udytHR2Q0Y01OclIvclg3S1JFRDcvU21CU3YKRm5HT0xxZURITVIvRXFOeFJibGRoZnk0Z2ZoT0pIdDZjdGs1WFB2SXRJWFdMY3E4V1kxUVhPcnhjZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f6998cf3-6c53-4514-a83c-94b667bd7481.k8s.ondigitalocean.com
  name: do-fra1-sikademo2
contexts:
- context:
    cluster: do-fra1-sikademo2
    user: do-fra1-sikademo2-admin
  name: do-fra1-sikademo2
current-context: do-fra1-sikademo2
users:
- name: do-fra1-sikademo2-admin
  user:
    token: dop_v1_8fec4e7634e5063edf0907f820922f5c0712567f2d1c13d2c01309e09d0b6a08
