---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secret-example
  namespace: training
spec:
  encryptedData:
    TEXT: AgB6ZG8ngbQ9DhVPjjhdZq9YPZRHY5B0IouHTNNaloja+rzZvgtKFBf3Jg3DvYkeYVAI8L6SFKdSpb9Ro9s04s1S9OJmQ3fHDM26Cj/YtL9XpkRpqDXuo9nMgdTjHffk8E87iO0wLRiXz5H+eYvq4TOh3N+1Vos/Us1E4uTlzbUaWsj8WFS9yoWwU/R40wlMnAIdvAADQ7szRbJBuSx2/2A6bUkR3ctwyruID+/IArZH/vp7/5Q1dxELeL/jmvghLhIqvJCvJWvv7ukz43gBqtf4LSwfvspEGnopcy7mx4Zd6BJt+pSYwZKgfc/qT7HxVGkHn6dCaP2oP72o9DHlDjsv+H+e1Q48/vrOt64f4u5FTO3sVQTDaSQcBRUuBoZ52y64jvEKCHdoNEUIs4RKRxd16Evgy0MomjC4DK6I+hqzku7TdD6kfUPzU9VqpjODiCOWL316kRc/WzjlzJq+G/eMkGLmK8yv5OnKiGbTV6OzIYB8ezsoHLzTWjd4alwGBCl7/Dn7afWmOxMNNYLnVL7l/4EmS7X+QZXrqb1ZYsTxaLrHT85QwCY5aBHUhbcTqLcI+lMSiha7VbdxcnqIuW6+/puz+0knXS0viS+4VvhNWQMJ+Ng81TK+a55Mvl3cP5QCijKNMZ+Nftwhl1ZsURCSuKP3ZXWdH26DK/oPu9h3bIdFffC+86tFEk1EBqlTR3c1TLO3qpnVcYVvuQ9FzNrqdz4Mm2s=
  template:
    metadata:
      name: sealed-secret-example
      namespace: training
