apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: ceps-dfx
  namespace: kafka
  labels:
    strimzi.io/cluster: ceps
spec:
  topicName: dfx
  partitions: 9
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
