apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dhl-example-helm2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    namespace: dhl-example-helm2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2026-05-13_dhl_example.git
    path: kubernetes/chart
    helm:
      valueFiles:
        - ../values/helm2.values.yaml