apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: flux-system
spec:
  url: https://github.com/sika-training-examples/2026-05-27-t-mobile-gitops-example.git
  timeout: 60s
  interval: 1m0s
  ref:
    branch: master
