---
- name: Handlers Example
  hosts: all
  gather_facts: false

  tasks:
    - name: Create file foo
      copy:
        content: "Hello World\n"
        dest: /tmp/hello-foo
        owner: root
        group: root
        mode: 0644
      register: xxx

    - name: debug
      debug:
        var: xxx