# required variables:
#
#  ARTIFACTORY: "artifactory.sikademo.com"
#  ARTIFACTORY_USER: "admin"
#  ARTIFACTORY_PASSWORD: "password"
#  ARTIFACTORY_DOCKER_PREFIX: "artifactory.sikademo.com/demo-docker"

image: sikalabs/ci

stages:
  - build
  - release

build-branch:
  stage: build
  only:
    - branches
  variables:
    TAG: $CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    IMAGE: $ARTIFACTORY_DOCKER_PREFIX/counter-backend:$TAG
  script:
    - docker login $ARTIFACTORY -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

build-tag:
  stage: build
  only:
    - tags
  variables:
    TAG: $CI_COMMIT_TAG
    IMAGE: $ARTIFACTORY_DOCKER_PREFIX/counter-backend:$TAG
  script:
    - docker login $ARTIFACTORY -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

release:
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean
