apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ondrej
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'ondrej'
    server: 'https://kubernetes.default.svc'
  - namespace: 'ondrej-counter'
    server: 'https://kubernetes.default.svc'
  - namespace: 'ondrej-hello-ondrej'
    server: 'https://kubernetes.default.svc'
  - namespace: 'openshift-config-managed'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'
