apiVersion: v1
kind: Config
clusters:
- name: "k3d"
  cluster:
    server: "https://rancher0.sikademo.com/k8s/clusters/c-m-m8rbh7kq"

users:
- name: "k3d"
  user:
    token: "kubeconfig-user-2ddjn2c2d9:2qt6zfdzt6xwfffn9l8gbhcgxcqwlq5j8s48p7rrvxg6hmsj9ltcl5"


contexts:
- name: "k3d"
  context:
    user: "k3d"
    cluster: "k3d"

current-context: "k3d"
