FROM debian:12-slim
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    python3=3.11.2-1+b1 \
    python3-pip=23.0.1+dfsg-1 && \
  rm -rf /var/lib/apt/lists/
WORKDIR /app
COPY requirements.txt .
RUN pip3 install -r requirements.txt --break-system-packages --no-cache-dir
COPY . .
CMD ["python3", "app.py"]
EXPOSE 80
