apiVersion: v1
kind: Secret
metadata:
  name: repo-oci-hello-egd
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  enableOCI: "true"
  url: registry.sikademo.com/docker/hello-egd
  username: ondrejsika
  password: asdfasdf
