apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  ttlSecondsAfterFinished: 20
  activeDeadlineSeconds: 600
  template:
    metadata:
      name: pi
    spec:
      # restartPolicy: Never
      restartPolicy: OnFailure
      containers:
        - name: main
          image: sikalabs/slu:v0.71.0
          command: ["/bin/bash", "-c"]
          args: ["slu chaos-monkey random-status-code"]
