apiVersion: v1
kind: Config
clusters:
- name: "production"
  cluster:
    server: "https://rancherb.cpas.cz/k8s/clusters/c-2qjwf"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYRENDQ\
      WtTZ0F3SUJBZ0lRWFpEdkxoTzU3THBJSGxWK3ljVFZkakFOQmdrcWhraUc5dzBCQVFzRkFEQS8KT\
      VFzd0NRWURWUVFHRXdKRFdqRVpNQmNHQTFVRUNoTVFRMlZ6YTJFZ2NHOXFhWE4wYjNadVlURVZNQ\
      k1HQTFVRQpBeE1NUTFCQlV5QlNiMjkwSUVOQk1CNFhEVEV4TURRd05UQTNNVFV5TjFvWERUSTJNR\
      FF3TlRBM01qVXlObG93ClB6RUxNQWtHQTFVRUJoTUNRMW94R1RBWEJnTlZCQW9URUVObGMydGhJS\
      EJ2YW1semRHOTJibUV4RlRBVEJnTlYKQkFNVERFTlFRVk1nVW05dmRDQkRRVENDQVNJd0RRWUpLb\
      1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBTWJFSlhkZzEybFpCRGJhczlMRXRLR3o0T\
      zBTdFFpd2N6Ly9pWXJnN1IrbHFIbVRyY0ZtQkJKajVObUswcFRhClNteVVjMjQ2VEtyaUR3bTlXQ\
      WduWnR2S1pIdUtyb1lJeFBhdSsxeTk3cHNxcUJacEhqdDk3VDgwUDFzdUI1WmMKeUNqUG82NnBxc\
      nBCMjU3MzIwemVvbDlxaDg4Zkl0aHh2bGcrWkVuMVhDUzdjOHBCejR6NFVKZTk1Ylk1L3ozegp6e\
      E1OalJzb3Q2eXdOT2tYWDlabEszNlFPb2ZUWlV6M3lLRVN1b2RrYTJiZy9YaWZ6OUJXZ2ZOUlYxd\
      DUvNldoCnJuUEVIek93WjlTYytWd2VraUMzUnl6Qzh3ZmhvUFY1R3kxT2loOXA2Z1NUNmt3TXY0S\
      2FCNXVoVHNVMnBldG0KaWREbEVZc2FwQ0dITHVHUExrTkp3VlVDQXdFQUFhTlVNRkl3Q3dZRFZSM\
      FBCQVFEQWdHR01CSUdBMVVkRXdFQgovd1FJTUFZQkFmOENBUUV3SFFZRFZSME9CQllFRkpNN0Vqc\
      W4yaTUvRUgwbTlBa3AvcE10UjNORk1CQUdDU3NHCkFRUUJnamNWQVFRREFnRUFNQTBHQ1NxR1NJY\
      jNEUUVCQ3dVQUE0SUJBUUFzNUR3bWM2Skw2T0tzM21FeUJ5cU4Kb2tlRVM0UDNad1R0dUkzeHJWd\
      HM2SHlsdm9LMitWOElwOFdQN0ovaVhNeXp5dTdmNHZHejFOd1lPa29ZYnpvUwowSWh0MVRXc1BhQ\
      zhQOUUweU5WVDBhMmpOakphNWdxTnE1OG5kUmJSTjhhN2hLb3RWa3VCMkxURTk4TlVtcXQ2CjViR\
      DI4SGNxUXFXNlUvNWlyWlFlSEIxd0NhT1F5czNCNnBNRXc1Y3QyRmNJSkNISndqZ1VsODZyaGF3b\
      GpENXMKNGxudnRkRWEwWXdMblhnMkNLdXhJM3JXMGpHQ1JxMDFNRUpiYlYyTzk3dzNaTDZWMmNUc\
      Fo4ZHhBK1pPS2ZmLwpOanFtdHZxckgrK05vOFFYNk5pYjdrempoMUVnS1Y4WDBLaVFpQ2FzNDVre\
      StHeHlIM3NOYTZHZklISVNxbGVZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KCi0tLS0tQkVHS\
      U4gQ0VSVElGSUNBVEUtLS0tLQpNSUlGdERDQ0JKeWdBd0lCQWdJS1lRV05Zd0FBQUFBQUN6QU5CZ\
      2txaGtpRzl3MEJBUXNGQURBL01Rc3dDUVlEClZRUUdFd0pEV2pFWk1CY0dBMVVFQ2hNUVEyVnphM\
      kVnY0c5cWFYTjBiM1p1WVRFVk1CTUdBMVVFQXhNTVExQkIKVXlCU2IyOTBJRU5CTUI0WERURTVNR\
      Gd3TnpFeU1UQXdOMW9YRFRJMk1EUXdOVEEzTWpVeU5sb3dRakVMTUFrRwpBMVVFQmhNQ1Exb3hHV\
      EFYQmdOVkJBb1RFRU5sYzJ0aElIQnZhbWx6ZEc5MmJtRXhHREFXQmdOVkJBTVREME5RClFWTWdTW\
      E56ZFdsdVp5QkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNN\
      mwKMDY4M1h6U1JaSmZlWGZTSmRWM3VYWEV0NmtXSUd2RHIxQWxyUTRMa1hsS1plTzRzVlhBcVphQ\
      UxkVzIvS3V1UwpjUU9VcVlYcWU0M3E0bHRiMUNoUGx2dlhrcGl0aHVpejQwQUlqOG9peHVBVjZIN\
      jBhbmViL3ZXbVpUa3RkVDJoCm1lZUlNVmFXY0lrR2NvR0pHSFJ6L28yMS9oS2FUTFczeFRwbksyW\
      kJXaVhYaUJGZzNSdFM4M1hRUmduNDhWQksKQWZoVlpxZnpvYk4zSkRnY216VDdWT1Qyak5VVEwrc\
      jB0a0ZIQ1hsM1ZHVENZOWh3cW1nQ1BpbFMvS0pndDYxVgpiVTFEdXlhY3N2VFlCNlcydXVRYXcya\
      lFZaFJhRXpmdjZLdjgvT0J1MnZIdUV4SFZRODJnS2VEbCtnWkp0ODFDCllEM1pJUEtZZ2VSZFFkS\
      nB0RGNDQXdFQUFhT0NBcTB3Z2dLcE1CQUdDU3NHQVFRQmdqY1ZBUVFEQWdFQk1DTUcKQ1NzR0FRU\
      UJnamNWQWdRV0JCUVphQTlOTDFKU0N5WkQrNnZuWjF1eTlTak52akFkQmdOVkhRNEVGZ1FVbGhmV\
      QpWSmhDaVdsejAvWGl4TlRRcWdlN1BsY3dHUVlKS3dZQkJBR0NOeFFDQkF3ZUNnQlRBSFVBWWdCR\
      EFFRXdDd1lEClZSMFBCQVFEQWdHR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdId1lEVlIwa\
      kJCZ3dGb0FVa3pzU09xZmEKTG44UWZTYjBDU24ra3kxSGMwVXdnZm9HQTFVZEh3U0I4akNCN3pDQ\
      jdLQ0I2YUNCNW9ZcWFIUjBjRG92TDNCcgphUzVqY0dGekxtTjZMMk5oTDBOUVFWTWxNakJTYjI5M\
      EpUSXdRMEV1WTNKc2hvRzNiR1JoY0Rvdkx5OURUajFEClVFRlRKVEl3VW05dmRDVXlNRU5CTEVOT\
      1BVTmFRMU5EVUVGVFVrTkJMRU5PUFVORVVDeERUajFRZFdKc2FXTWwKTWpCTFpYa2xNakJUWlhKM\
      mFXTmxjeXhEVGoxVFpYSjJhV05sY3l4RFRqMURiMjVtYVdkMWNtRjBhVzl1TEVSRApQV053WVhNc\
      1JFTTlZM28vWTJWeWRHbG1hV05oZEdWU1pYWnZZMkYwYVc5dVRHbHpkRDlpWVhObFAyOWlhbVZqC\
      mRFTnNZWE56UFdOU1RFUnBjM1J5YVdKMWRHbHZibEJ2YVc1ME1JSDJCZ2dyQmdFRkJRY0JBUVNCN\
      lRDQjVqQTIKQmdnckJnRUZCUWN3QW9ZcWFIUjBjRG92TDNCcmFTNWpjR0Z6TG1ONkwyTmhMME5RU\
      VZNbE1qQlNiMjkwSlRJdwpRMEV1WTNKME1JR3JCZ2dyQmdFRkJRY3dBb2FCbm14a1lYQTZMeTh2U\
      TA0OVExQkJVeVV5TUZKdmIzUWxNakJEClFTeERUajFCU1VFc1EwNDlVSFZpYkdsakpUSXdTMlY1S\
      lRJd1UyVnlkbWxqWlhNc1EwNDlVMlZ5ZG1salpYTXMKUTA0OVEyOXVabWxuZFhKaGRHbHZiaXhFU\
      XoxamNHRnpMRVJEUFdONlAyTkJRMlZ5ZEdsbWFXTmhkR1UvWW1GegpaVDl2WW1wbFkzUkRiR0Z6Y\
      3oxalpYSjBhV1pwWTJGMGFXOXVRWFYwYUc5eWFYUjVNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElCQ\
      VFBNmNXTnBiMEtVdU5VV2JoZHNLUmtyWGxVNUdCVEFHdUdyZVVPOXRwaTdyWUdLamtNMkRPbzUKa\
      jhiWFdvd255VWEzWlBOMW9GMFR3eDJWcjdaVlRYT3c2TXcwekFubTZhMUNFajlMbXg5Q3ZWMUY2S\
      U5mMk44egoxQkIwWTI5UWJSajVCNDBTeWFMdzZES0E1U3ZVRVJpV05GbkNxd0JnYW9URTl4Rk1uQ\
      2N6dWptNWVwMFNQOFozCm5rRWpDandWRGN5clA1ZlZvV3FmU1h2TzlkaTZVUkdHa1Yrc1JTSmJkM\
      0J5LzJyVE92bWttSVhZUXpEYlE5c04KcGs4SUR1NzZ1QktaemJaQmVxbk1zamZWN3ZnNElkSFJnO\
      WdlWjFHL2lrcCtPT3dTcHQ3bjVjM0YzMWVlVkdzMAoxbmNCRFg5SWRmNzFkWk5FcFlHbWlWY1FxN\
      FAwY1lXWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "production"
  user:
    token: "kubeconfig-u-xhsphbc5mjvq7mf:f8fjh7x4pcjs66rv5vjjbf4nhdrvvrg2sgdx5g9n8g6xdswjgzg75t"


contexts:
- name: "production"
  context:
    user: "production"
    cluster: "production"

current-context: "production"
