services:
  web:
    image: ghcr.io/sikalabs/hello-world-server
    environment:
      TEXT: "54"
    deploy:
      replicas: 4

  caddy:
    build: .
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN?}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
