apiVersion: config.openshift.io/v1
kind: DNS
metadata:
  creationTimestamp: null
  name: cluster
spec:
  baseDomain: okd94.aws0.sikademo.com
  privateZone:
    tags:
      Name: okd94-8czw9-int
      kubernetes.io/cluster/okd94-8czw9: owned
  publicZone:
    id: Z03093231W3LZLT5QT1EP
status: {}
