services:
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy-data:/data
      - caddy-config:/config

  counter:
    build: .
    image: ttl.sh/dte/simple-compose/counter
    depends_on:
      - redis
    environment:
      REDIS: redis
  redis:
    image: redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  caddy-data:
  caddy-config:
