apiVersion: apps/v1
kind: Deployment
metadata:
  name: d300-pc1000
  annotations:
    kubernetes.io/change-cause: yellow
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: d300
  replicas: 300
  template:
    metadata:
      labels:
        app: d300
    spec:
      priorityClassName: pc1000
      containers:
        - name: main
          image: ondrejsika/training-example
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 20Mi
              cpu: 20m