setup.dashboards.enabled: true

filebeat.modules:
  - module: traefik
    access:
      enabled: true
      input:
        type: container
        paths:
          - "/var/lib/docker/containers/*/*.log"

processors:
  - drop_event:
      when:
        has_fields:
          - error

output.elasticsearch:
  hosts:
    - https://es.k8s.sikademo.com:443
  username: elastic
  password: q3fv4NT1YB7L0yL4X27M30WI
