image: ghcr.io/sikalabs/ci

variables:
  IMAGE_BACKEND: $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_REF_SLUG
  IMAGE_FRONTEND: $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_REF_SLUG
  IMAGE_CADDY: $CI_REGISTRY_IMAGE/caddy:$CI_COMMIT_REF_SLUG
  IMAGE_TESTS: $CI_REGISTRY_IMAGE/tests:$CI_COMMIT_REF_SLUG

stages:
  - build
  - test
  - deploy

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login  "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin

build:
  stage: build
  variables:
    DOCKER_BUILDKIT: "1"
    COMPOSE_FILE: "compose.yml:compose.caddy.yml:compose.tests.yml"
  script:
    - docker compose build --pull --progress=plain
    - docker compose push

.test:
  stage: test
  except:
    - master
  variables:
    COMPOSE_FILE: "compose.yml:compose.tests.yml"
    COMPOSE_PROJECT_NAME: "ci_$CI_JOB_ID"
  after_script:
    - docker compose down --remove-orphans

test-tests:
  extends: .test
  script:
    - docker compose pull
    - docker compose run tests

test-ab-be-api:
  extends: .test
  script:
    - docker compose pull
    - docker compose run ab-be-api

test-ab-be:
  extends: .test
  script:
    - docker compose pull
    - docker compose run ab-be

test-ab-fe:
  extends: .test
  script:
    - docker compose pull
    - docker compose run ab-fe

deploy:
  stage: deploy
  variables:
    DOCKER_HOST: "ssh://root@docker.sikademo.com"
    TRAEFIK_NAME: "counter-$CI_COMMIT_REF_SLUG"
    COMPOSE_PROJECT_NAME: "counter-$CI_COMMIT_REF_SLUG"
    HOST: "counter-$CI_COMMIT_REF_SLUG.docker.sikademo.com"
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H docker.sikademo.com >> ~/.ssh/known_hosts
    - make use-traefik
    - docker compose pull
    - make up
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: "https://$HOST"
    on_stop: deploy_stop

deploy_stop:
  stage: deploy
  when: manual
  variables:
    DOCKER_HOST: "ssh://root@docker.sikademo.com"
    GIT_STRATEGY: none
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H docker.sikademo.com >> ~/.ssh/known_hosts
    - docker ps -f label=com.docker.compose.project=counter-$CI_COMMIT_REF_SLUG --format "{{.ID}}" | xargs -r docker rm -f
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
