apiVersion: v1
kind: Config
clusters:
  - cluster:
        server: http://lab0.sikademo.com:8001
    name: do-fra1-sikademo
contexts:
  - context:
        cluster: do-fra1-sikademo
        user: do-fra1-sikademo-admin
        namespace: ondrejsika
    name: do-fra1-sikademo
current-context: do-fra1-sikademo