apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-pvc
spec:
  volumeName: pvc-6a47f533-420b-4c67-b5ad-817aa098b8e5
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
