apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ak-example
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ak-example-manual.k8s.sikademo.com
      secretName: ak-example
  rules:
    - host: ak-example-manual.k8s.sikademo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ak-example
                port:
                  number: 80
    