host: pss-counter-be.k8s.sikademo.com
env:
  BACKEND: mongodb
  VAULT_ADDR: http://vault.vault:8200
  VAULT_K8S_ROLE: counter-prod
  VAULT_KV_MOUNT: secret
  VAULT_KV_PATH: pss/project_counter/prod/be-env
  VAULT_KV_KEY: MONGODB_URI
